#ifndef CORPCHATNETWORKLIB_GLOBAL_H
#define CORPCHATNETWORKLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CORPCHATNETWORKLIB_LIBRARY)
#  define CORPCHATNETWORKLIB_EXPORT Q_DECL_EXPORT
#else
#  define CORPCHATNETWORKLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CORPCHATNETWORKLIB_GLOBAL_H
